#
# Test directories need a 'Makefile' which has a 'all' and 'clean' target.
# That is the only requirement!
#

NETSIM_DIR=${ROOT}/netsim
NETSCRIPT_DIR=${ROOT}/netscript

all:
	@echo "Finished template tests"
clean:
	@echo "Finished template cleaning"