#!/bin/sh
#
# Gets file list on standard input and RPM_BUILD_ROOT as first parameter
# and searches for omitted files (not counting directories).
# Returns it's output on standard output.
#
# filon@pld.org.pl

RPM_BUILD_ROOT=$1

if [ ! -d "$RPM_BUILD_ROOT" ] ; then
	cat > /dev/null
	exit 1
fi

[ "$TMPDIR" ] || TMPDIR=/tmp
FILES_DISK=`mktemp $TMPDIR/rpmXXXXXX`
FILES_RPM=`mktemp $TMPDIR/rpmXXXXXX`

find $RPM_BUILD_ROOT -type f | LC_ALL=C sort > $FILES_DISK
LC_ALL=C sort > $FILES_RPM

for f in `diff -d "$FILES_DISK" "$FILES_RPM" | grep "^< " | cut -c3-`; do
	echo $f | sed -e "s#^$RPM_BUILD_ROOT#   #g"
done

echo check disk:$FILES_DISK and rpm:$FILES_RPM
echo rm -f $FILES_DISK
echo rm -f $FILES_RPM
