
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[328] =
    {   0,
        0,    0,    0,    0,    0,    0,   64,   62,   61,   61,
       62,   56,   62,   55,   54,   62,   62,   41,   41,   62,
       52,   50,   53,   51,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   48,
       49,   60,   60,   60,   61,    0,   46,    0,    0,    0,
       44,   58,    0,   45,   40,    0,   41,    0,   41,   47,
       38,   38,    0,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   59,   42,    0,   44,    0,
       57,   44,    0,   45,   40,    0,   43,   39,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   33,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,    0,   44,    0,   44,    0,   45,
       43,   39,   38,   36,   38,   29,   38,   38,   38,   38,
       38,   38,   38,   38,   32,   38,   38,   38,   38,   38,
       38,   38,   34,    9,   38,   38,   38,   28,    0,   44,
       37,   38,   38,   38,   38,   38,   38,   35,   27,   38,
        0,   38,   38,   38,   38,   26,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   25,   38,    0,
        0,   38,   38,   38,    2,   24,   38,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,    0,    0,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   31,    0,   38,   38,   38,   38,   38,
       38,   23,   38,   38,   38,   38,   38,   38,   38,   30,
       13,   12,   38,   38,    8,   38,   38,   38,   38,   38,
       38,    4,   38,   38,    6,   14,   38,   38,   38,    7,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,    3,   38,   38,
       38,   38,   38,   38,   38,   38,   15,   38,   16,   38,
        5,   11,   38,   38,   38,   38,   38,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   10,
       21,   22,   38,   38,   38,   38,   38,   38,   17,   18,
       19,   38,   38,   38,   20,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    5,    6,    1,
        1,    7,    8,    9,    8,   10,   11,   12,   13,   14,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   22,   22,   23,   24,   25,
       26,   26,   27,   26,   26,   28,   29,   30,   26,   31,
       26,   32,   33,   34,   35,   26,   26,   36,   37,   26,
        1,   38,    1,    1,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   26,   26,   49,   50,   51,
       52,   53,   26,   54,   55,   56,   57,   58,   26,   59,
       60,   61,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    4,    3,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[335] =
    {   0,
        0,    2,    5,    0,   67,   69,  520,  521,   75,   77,
       69,  521,  481,  521,  521,   69,   78,   98,  148,  502,
      521,  521,  521,  521,    0,  496,  510,  483,  475,   39,
       43,   48,   39,  461,   52,   58,   39,  461,   67,  521,
      521,  521,  101,  500,  114,   71,  521,  507,   90,   95,
      194,  521,  506,  232,  272,  117,   92,    0,    0,  521,
        0,  480,  469,  471,  474,   95,  453,  458,   79,  453,
      449,  444,  460,  447,  438,  445,  441,   98,  448,  453,
      435,  438,  435,  434,  440,  521,  521,  156,  521,  484,
      521,  318,  165,  521,  117,  172,  176,  118,  453,  461,

      452,  429,  433,  436,  440,  440,  437,  422,  436,    0,
      435,  428,  434,  433,  423,  416,  415,  417,  411,  422,
      421,   96,  407,  420,  181,  250,  202,  521,  214,  277,
      521,  185,  438,    0,  434,    0,  417,  411,  401,  402,
      407,  411,  398,  404,  121,  410,  409,  410,  405,  392,
      403,  154,    0,    0,  392,  399,  404,    0,  218,  299,
        0,  414,  403,  395,  391,  383,  394,    0,    0,  389,
      221,  384,  383,  385,  390,    0,  389,  392,  375,  381,
      377,  378,  402,  369,  367,  367,  368,    0,  381,  369,
      367,  361,  360,  368,    0,    0,  373,  358,  373,  368,

      363,  371,  349,  354,  368,  358,  350,  348,  352,  351,
      350,  339,  347,  350,  348,  353,  334,  355,  340,  352,
      333,  339,  337,  521,  320,  309,  308,  317,  309,  317,
      310,    0,  313,  216,  312,  314,  314,  307,  309,  521,
        0,    0,  312,  305,    0,  288,  304,  317,  312,  313,
      198,    0,  290,  289,    0,    0,  292,  288,  291,    0,
      307,  297,  297,  284,  281,  288,  274,  260,  273,  264,
      270,  287,  272,  280,  117,  120,  279,    0,  257,  242,
      240,  249,  260,  251,  253,  249,    0,  248,    0,  247,
        0,    0,  219,  230,  232,  229,  246,  238,  233,  236,

      218,  199,  215,  214,  223,  212,  210,  209,  180,    0,
        0,    0,  179,  161,  160,  143,  133,  126,    0,    0,
        0,   96,  100,   86,    0,    0,  521,  367,  371,  375,
      379,  381,  385,  115
    } ;

static yyconst flex_int16_t yy_def[335] =
    {   0,
      328,  328,  327,    3,  329,  329,  327,  327,  327,  327,
      330,  327,  331,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  327,
      327,  327,  327,  327,  327,  330,  327,  330,  331,  331,
      327,  327,  333,  327,  327,  327,  327,  334,   19,  327,
      332,  332,  331,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  327,  327,  327,  327,  333,
      327,  327,  327,  327,  327,  327,  327,  334,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  327,  327,  327,  327,  327,  327,
      327,  327,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  327,  327,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      327,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  327,
      327,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  327,  327,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  327,  327,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  327,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  332,  332,    0,  327,  327,  327,
      327,  327,  327,  327
    } ;

static yyconst flex_int16_t yy_nxt[585] =
    {   0,
      327,    9,   10,    9,   10,    8,    9,   10,   11,   12,
       13,   14,    8,   15,   16,   17,   18,   19,   19,   19,
       20,   21,   22,   23,   24,   25,   25,   25,   25,   26,
       25,   25,   27,   25,   25,   25,   25,   25,   28,   25,
       25,   25,    8,   29,   25,   25,   30,   31,   25,   32,
       25,   25,   33,   34,   35,   25,   25,   25,   25,   36,
       37,   38,   39,   25,   25,   25,   40,   41,   43,   10,
       43,   10,   47,   44,   47,   44,   45,   45,   45,   45,
       51,   51,   51,   51,   52,   66,   68,   70,   53,   72,
       67,   75,   81,   73,   69,   87,   71,  327,   82,   76,

       49,   77,   45,   45,   78,   79,   48,   54,   48,   55,
       55,   55,   55,   80,   84,   45,   45,   98,   85,   57,
      106,   56,  171,  171,   96,   57,   57,   50,   97,   97,
       97,   97,   57,   58,  102,  107,  326,  116,  325,  155,
       57,   56,  103,  156,   95,  132,   57,  324,   57,  117,
      286,   95,  132,  288,   57,  287,   58,   54,  289,   59,
       59,   59,   59,  125,  323,   95,  132,  126,  126,  126,
      126,   56,  129,   95,  132,   57,  130,  130,  130,  130,
      322,  321,   57,   97,   97,   97,   97,   97,   97,   97,
       97,   56,  126,  126,  126,  126,   57,  178,  320,  319,

      131,  179,  318,  131,   57,   51,   51,   51,   51,  159,
      264,  265,  132,  160,  160,  160,  160,   88,   89,  132,
      131,   89,  171,  171,  131,  130,  130,  130,  130,  160,
      160,  160,  160,  132,  266,  317,  248,   88,   89,  249,
      250,  132,   89,   92,   92,   92,   92,  316,  315,  251,
      314,  313,  312,  311,  310,   93,   94,  309,  308,   94,
      307,  126,  126,  126,  126,  306,  305,  304,  190,  191,
      303,  302,  301,  300,   89,   93,   94,   89,  299,  298,
       94,   54,  297,   55,   55,   55,   55,  296,  130,  130,
      130,  130,  295,  294,   89,   56,  293,  292,   89,   95,

      291,   94,  290,  285,   94,  284,   95,  283,  282,  281,
      160,  160,  160,  160,  280,   56,  279,  278,  277,  276,
       95,   94,  275,  128,  274,   94,  128,  273,   95,   92,
       92,   92,   92,  272,  271,  270,  269,  268,  267,  263,
      262,  127,  128,  128,  261,  128,  260,  128,  259,  258,
      257,  256,  255,  254,  253,  252,  247,  246,  245,  244,
      243,  127,  128,  242,  241,  240,  128,    8,    8,    8,
        8,   42,   42,   42,   42,   46,   46,   46,   46,   49,
      239,   49,   49,   61,   61,   90,   90,   90,   90,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,

      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  177,  176,  175,  174,
      173,  172,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  158,  157,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,   91,  124,  123,  122,
      121,  120,  119,  118,  115,  114,  113,  112,  111,  110,

      109,  108,  105,  104,  101,  100,   50,   99,   91,  327,
       86,   83,   74,   65,   64,   63,   62,   60,   50,  327,
        7,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327
    } ;

static yyconst flex_int16_t yy_chk[585] =
    {   0,
        0,    1,    1,    2,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        6,    6,   11,    5,   46,    6,    9,    9,   10,   10,
       16,   16,   16,   16,   17,   30,   31,   32,   17,   33,
       30,   35,   37,   33,   31,   49,   32,   50,   37,   35,

       50,   36,   43,   43,   36,   36,   11,   18,   46,   18,
       18,   18,   18,   36,   39,   45,   45,  334,   39,   57,
       69,   18,  145,  145,   56,   18,   57,   49,   56,   56,
       56,   56,   18,   18,   66,   69,  324,   78,  323,  122,
       57,   18,   66,  122,   95,   98,   18,  322,   57,   78,
      275,   95,   98,  276,   18,  275,   18,   19,  276,   19,
       19,   19,   19,   88,  318,   95,   98,   88,   88,   88,
       88,   19,   93,   95,   98,   19,   93,   93,   93,   93,
      317,  316,   19,   96,   96,   96,   96,   97,   97,   97,
       97,   19,  125,  125,  125,  125,   19,  152,  315,  314,

       97,  152,  313,   97,   19,   51,   51,   51,   51,  127,
      251,  251,  132,  127,  127,  127,  127,   51,   51,  132,
       97,   51,  171,  171,   97,  129,  129,  129,  129,  159,
      159,  159,  159,  132,  251,  309,  234,   51,   51,  234,
      234,  132,   51,   54,   54,   54,   54,  308,  307,  234,
      306,  305,  304,  303,  302,   54,   54,  301,  300,   54,
      299,  126,  126,  126,  126,  298,  297,  296,  171,  171,
      295,  294,  293,  290,  126,   54,   54,  126,  288,  286,
       54,   55,  285,   55,   55,   55,   55,  284,  130,  130,
      130,  130,  283,  282,  126,   55,  281,  280,  126,   55,

      279,  130,  277,  274,  130,  273,   55,  272,  271,  270,
      160,  160,  160,  160,  269,   55,  268,  267,  266,  265,
       55,  130,  264,  160,  263,  130,  160,  262,   55,   92,
       92,   92,   92,  261,  259,  258,  257,  254,  253,  250,
      249,   92,   92,  160,  248,   92,  247,  160,  246,  244,
      243,  239,  238,  237,  236,  235,  233,  231,  230,  229,
      228,   92,   92,  227,  226,  225,   92,  328,  328,  328,
      328,  329,  329,  329,  329,  330,  330,  330,  330,  331,
      223,  331,  331,  332,  332,  333,  333,  333,  333,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,

      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  194,  193,  192,  191,  190,
      189,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  175,  174,  173,  172,  170,  167,  166,  165,
      164,  163,  162,  157,  156,  155,  151,  150,  149,  148,
      147,  146,  144,  143,  142,  141,  140,  139,  138,  137,
      135,  133,  124,  123,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  111,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   99,   90,   85,   84,   83,
       82,   81,   80,   79,   77,   76,   75,   74,   73,   72,

       71,   70,   68,   67,   65,   64,   63,   62,   53,   48,
       44,   38,   34,   29,   28,   27,   26,   20,   13,    7,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
#line 9 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"

/*
 * scehma.l :- used to construct configurable entities
 *
 */

#include <stdio.h>
#include <string.h>
#include "generator_parser.h"


#line 701 "lex.yy.c"

#define INITIAL 0
#define NORM 1
#define CMT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 23 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"

								{BEGIN NORM;}
#line 888 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 328 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 521 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return STATE_CFG; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return SHARED; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONFIGURABLE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CHILD_TYPE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return DEFAULT_VALUE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return DOC_STR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 31 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return VISUALZIED; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return STATISTIC; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return TYPE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return UNSERIALIZE_FCT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return SERIALIZE_FCT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return MIN_COUNT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return MAX_COUNT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return IS_ALIASED; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return T1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return T2; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return T1_TPL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return T2_TPL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return TYPEID; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return FILENAME; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return ALIAS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return EMPTY; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return UNSIGNED; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return SIGNED; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return DOUBLE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return SHORT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return FLOAT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return VOID; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CHAR; }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 55 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup("long long"); return LONG_LONG; }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 56 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup("long int"); return LONG_INT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return LONG; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return INT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 69 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return CONSTANT; }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 75 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext+1); yylval.str[strlen(yylval.str)-1]='\0'; return STRING_LITERAL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 77 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return COLONS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return LCURL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 79 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return RCURL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 80 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return LANGLE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 81 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return RANGLE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 82 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return SEMI; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 83 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return EQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 84 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return COMMA; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 85 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return STAR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 86 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ yylval.str=strdup(yytext); return AMPR; }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 87 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 88 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ BEGIN CMT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 89 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ BEGIN NORM; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 90 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 92 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
{ printf("\nERROR: skipping %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 95 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"
ECHO;
	YY_BREAK
#line 1292 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NORM):
case YY_STATE_EOF(CMT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 328 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 328 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 327);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 95 "/Users/liux/Workspace/primogeni/netsim/tools/ssfnet-xlate/generator.l"



int lex_setup(const char* file)
{
  yyin = fopen(file, "r");
  if(!yyin) {
	fprintf(stderr, "cant open '%s'\n",file);
	exit(100);
  }
  yyrestart(yyin);
  return 0;
}

void lex_teardown()
{
  yy_delete_buffer(YY_CURRENT_BUFFER);
  fclose(yyin);
  yy_switch_to_buffer(0);
}

